### PR TITLE
Remove deprecated usage of set query buffer functions

### PR DESCRIPTION
**Pull request by Shelnutt2**
Remove deprecated usage of set query buffer functions. This is part 1 as we need to also migrate to the newer, better APIs for just `[Get|Set][Data|Offsets|Validity]Buffer`

### CODE REVIEW

**Comment by jdblischak** [comment]
I tested this PR against a nightly build of libtiledb in a local Ubuntu setup. All the tests pass

Context: I am building a GitHub Actions pipeline to run nightly tests of the TileDB-Go branch "master" against the libtiledb branch "dev". Until this PR is merged, the nightly builds will fail

<details>
<summary>Details
</summary>

```sh
git log -n 1 --oneline
## 8fc2de7 (HEAD -> master, upstream/master, origin/master, origin/HEAD) Use a safe(r) internal byte-storage type in Buffer. (#247)
# Install go and libtiledb (nightly) with conda/mamba 
mamba create --yes -n goenv -c conda-forge gcc go=1.18
mamba activate goenv
go version
## go version go1.18.5 linux/amd64
mamba install -c "tiledb/label/nightlies" tiledb
mamba list tiledb
## #
## # Name                    Version                   Build  Channel
## tiledb                    2.15.0.2023_01_11      h42dd806_0    tiledb/label/nightlies
export CPATH=$CONDA_PREFIX/include
export LIBRARY_PATH=$CONDA_PREFIX/lib
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib
go get -t .
## go: downloading github.com/mattn/go-pointer v0.0.1
## go: downloading go4.org/unsafe/assume-no-moving-gc v0.0.0-20220617031537-928513b29760
## go: downloading github.com/stretchr/testify v1.6.1
## go: downloading github.com/pmezard/go-difflib v1.0.0
## go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
## go: downloading github.com/davecgh/go-spew v1.1.0

git checkout upstream/stefannaglee/sc-24303/tiledb-go-build-fails-after-3733

go test -v ./...
```

</details>


The full test results are available in [nightly-test-results.txt](https://github.com/TileDB-Inc/TileDB-Go/files/10405770/nightly-test-results.txt)

**Comment by jdblischak** [comment]
In case it could be helpful, here are also the logs to nightly builds from my fork:

* branch "master" [fails](https://github.com/jdblischak/TileDB-Go/actions/runs/3905903662/jobs/6673457055#step:5:25)

```sh
# github.com/TileDB-Inc/TileDB-Go
./query.go:1440:9: could not determine kind of name for C.tiledb_query_get_buffer
./query.go:1600:8: could not determine kind of name for C.tiledb_query_get_buffer_nullable
./query.go:2378:9: could not determine kind of name for C.tiledb_query_get_buffer_var
./query.go:2576:8: could not determine kind of name for C.tiledb_query_get_buffer_var_nullable
./query.go:202:9: could not determine kind of name for C.tiledb_query_set_buffer
./query.go:452:9: could not determine kind of name for C.tiledb_query_set_buffer_nullable
./query.go:1702:9: could not determine kind of name for C.tiledb_query_set_buffer_var
./query.go:1963:9: could not determine kind of name for C.tiledb_query_set_buffer_var_nullable
FAIL	github.com/TileDB-Inc/TileDB-Go [build failed]
?   	github.com/TileDB-Inc/TileDB-Go/bytesizes	[no test files]
FAIL	github.com/TileDB-Inc/TileDB-Go/examples [build failed]
```

* This PR [passes](https://github.com/jdblischak/TileDB-Go/actions/runs/3905937191/jobs/6673535254#step:5:49)

**Comment by jdblischak** [comment]
Update: I was also able to build this PR against the nightly libtiledb on the GitHub Actions image `macos-11` after setting `-DTILEDB_WEBP=OFF`

**Review by snagles — APPROVED** [review]

**Comment by snagles** [comment]
cc @anastasop

**Pull request merged**
